=== brogan/Loom_2026/bezier/resources/dtd/animator.dtd
<!ELEMENT animator (name, keys)>

    <!ELEMENT name (#PCDATA)>
    <!ELEMENT keys (key+)>
       <!ELEMENT key (duration, tweenMode, easeMode, oscillator, scaleX, scaleY, rotationAngle, rotationOffset, transX, transY, renderer)>
       		<!ELEMENT duration (#PCDATA)>
       		<!ELEMENT tweenMode (#PCDATA)>
       		<!ELEMENT easeMode (#PCDATA)>
       		<!ELEMENT oscillator (#PCDATA)>
    		<!ELEMENT scaleX (#PCDATA)>
    		<!ELEMENT scaleY (#PCDATA)>
    		<!ELEMENT rotationAngle (#PCDATA)>
    		<!ELEMENT rotationOffset (#PCDATA)>
    		<!ELEMENT transX (#PCDATA)>
    		<!ELEMENT transY (#PCDATA)>
    		<!ELEMENT renderer (#PCDATA)>

=== brogan/Loom_2026/bezier/resources/animators/random_transX_5.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE animator SYSTEM "../dtd/animator.dtd">

<animator>

	<name>random_transX_5</name>
	<keys>
		<key>
			<duration>180</duration>
			<tweenMode>RANDOM</tweenMode>
			<easeMode>LINEAR</easeMode>
			<oscillator>none</oscillator>
			<scaleX>3</scaleX>
			<scaleY>3</scaleY>
			<rotationAngle>0</rotationAngle>
			<rotationOffset>0</rotationOffset>
			<transX>5</transX>
			<transY>0</transY>
			<renderer>F_blue_255</renderer>
		</key>
	</keys>

</animator>

=== brogan/Loom_2026/bezier/resources/animators/triangle.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE animator SYSTEM "../dtd/animator.dtd">

<animator>

	<name>triangle</name>
	<keys>
		<key>
			<duration>60</duration>
			<tweenMode>TWEENING</tweenMode>
			<easeMode>EASEINQUAD</easeMode>
			<oscillator>none</oscillator>
			<scaleX>1</scaleX>
			<scaleY>1</scaleY>
			<rotationAngle>0</rotationAngle>
			<rotationOffset>0</rotationOffset>
			<transX>-3</transX>
			<transY>3</transY>
			<renderer>F_blue_255</renderer>
		</key>
		<key>
			<duration>60</duration>
			<tweenMode>TWEENING</tweenMode>
			<easeMode>EASEINQUAD</easeMode>
			<oscillator>none</oscillator>
			<scaleX>1</scaleX>
			<scaleY>1</scaleY>
			<rotationAngle>0</rotationAngle>
			<rotationOffset>0</rotationOffset>
			<transX>0</transX>
			<transY>-3</transY>
			<renderer>F_blue_255</renderer>
		</key>
		<key>
			<duration>60</duration>
			<tweenMode>TWEENING</tweenMode>
			<easeMode>EASEINQUAD</easeMode>
			<oscillator>none</oscillator>
			<scaleX>1</scaleX>
			<scaleY>1</scaleY>
			<rotationAngle>0</rotationAngle>
			<rotationOffset>0</rotationOffset>
			<transX>3</transX>
			<transY>3</transY>
			<renderer>F_blue_255</renderer>
		</key>
	</keys>

</animator>

=== brogan/Loom_2026/bezier/resources/animators/weave_horizontal_X3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE animator SYSTEM "../dtd/animator.dtd">
<animator>
    <name>weave_horizontal_X3</name>
        <keys>
            <key>
                <duration>60.0</duration>
                <tweenMode>TWEENING</tweenMode>
                <easeMode>linear</easeMode>
                <oscillator>osc_01</oscillator>
                <scaleX>1.0</scaleX>
                <scaleY>1.0</scaleY>
                <rotationAngle>0.0</rotationAngle>
                <rotationOffset>0.0</rotationOffset>
                <transX>-3.0</transX>
                <transY>0.0</transY>
                <renderer>F_blue_255</renderer>
            </key>
            <key>
                <duration>60.0</duration>
                <tweenMode>TWEENING</tweenMode>
                <easeMode>linear</easeMode>
                <oscillator>osc_01</oscillator>
                <scaleX>1.0</scaleX>
                <scaleY>1.0</scaleY>
                <rotationAngle>0.0</rotationAngle>
                <rotationOffset>0.0</rotationOffset>
                <transX>3.0</transX>
                <transY>0.0</transY>
                <renderer>F_blue_255</renderer>
            </key>
        </keys>
</animator>

=== brogan/Loom_2026/bezier/resources/animators/star_ryb.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE animator SYSTEM "../dtd/animator.dtd">

<animator>

	<name>star_yrb</name>
	<keys>
		<key>
			<duration>60</duration>
			<tweenMode>TWEENING</tweenMode>
			<easeMode>EASEINQUAD</easeMode>
			<oscillator>none</oscillator>
			<scaleX>1</scaleX>
			<scaleY>1</scaleY>
			<rotationAngle>0</rotationAngle>
			<rotationOffset>0</rotationOffset>
			<transX>-2</transX>
			<transY>2</transY>
			<renderer>F_blue_10</renderer>
		</key>
		<key>
			<duration>60</duration>
			<tweenMode>TWEENING</tweenMode>
			<easeMode>EASEINQUAD</easeMode>
			<oscillator>none</oscillator>
			<scaleX>1</scaleX>
			<scaleY>1</scaleY>
			<rotationAngle>0</rotationAngle>
			<rotationOffset>0</rotationOffset>
			<transX>2.5</transX>
			<transY>-1</transY>
			<renderer>F_yell_10</renderer>
		</key>
		<key>
			<duration>60</duration>
			<tweenMode>TWEENING</tweenMode>
			<easeMode>EASEINQUAD</easeMode>
			<oscillator>none</oscillator>
			<scaleX>1</scaleX>
			<scaleY>1</scaleY>
			<rotationAngle>0</rotationAngle>
			<rotationOffset>0</rotationOffset>
			<transX>-2.5</transX>
			<transY>-1</transY>
			<renderer>F_red_10</renderer>
		</key>
		<key>
			<duration>60</duration>
			<tweenMode>TWEENING</tweenMode>
			<easeMode>EASEINQUAD</easeMode>
			<oscillator>none</oscillator>
			<scaleX>1</scaleX>
			<scaleY>1</scaleY>
			<rotationAngle>0</rotationAngle>
			<rotationOffset>0</rotationOffset>
			<transX>2</transX>
			<transY>2</transY>
			<renderer>F_blue_10</renderer>
		</key>
		<key>
			<duration>60</duration>
			<tweenMode>TWEENING</tweenMode>
			<easeMode>EASEINQUAD</easeMode>
			<oscillator>none</oscillator>
			<scaleX>1</scaleX>
			<scaleY>1</scaleY>
			<rotationAngle>0</rotationAngle>
			<rotationOffset>0</rotationOffset>
			<transX>0</transX>
			<transY>-2.5</transY>
			<renderer>F_red_10</renderer>
		</key>
	</keys>

</animator>

=== brogan/Loom_2026/bezier/resources/animators/flip_left_right.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE animator SYSTEM "../dtd/animator.dtd">
<animator>
    <name>flip_left_right</name>
    <keys>
        <key>
            <duration>30.0</duration>
            <tweenMode>TWEENING</tweenMode>
            <easeMode>easeInQuint</easeMode>
            <oscillator>none</oscillator>
            <scaleX>1.0</scaleX>
            <scaleY>1.0</scaleY>
            <rotationAngle>0.0</rotationAngle>
            <rotationOffset>0.0</rotationOffset>
            <transX>0.0</transX>
            <transY>0.0</transY>
            <renderer>F_blue_255</renderer>
        </key>
        <key>
            <duration>30.0</duration>
            <tweenMode>TWEENING</tweenMode>
            <easeMode>linear</easeMode>
            <oscillator>none</oscillator>
            <scaleX>0.0</scaleX>
            <scaleY>0.6</scaleY>
            <rotationAngle>0.0</rotationAngle>
            <rotationOffset>0.0</rotationOffset>
            <transX>0.0</transX>
            <transY>0.0</transY>
            <renderer>F_blue_255</renderer>
        </key>
        <key>
            <duration>30.0</duration>
            <tweenMode>TWEENING</tweenMode>
            <easeMode>easeInQuint</easeMode>
            <oscillator>none</oscillator>
            <scaleX>-1.0</scaleX>
            <scaleY>1.0</scaleY>
            <rotationAngle>0.0</rotationAngle>
            <rotationOffset>0.0</rotationOffset>
            <transX>0.0</transX>
            <transY>0.0</transY>
            <renderer>F_blue_255</renderer>
        </key>
        <key>
            <duration>30.0</duration>
            <tweenMode>TWEENING</tweenMode>
            <easeMode>linear</easeMode>
            <oscillator>none</oscillator>
            <scaleX>0.0</scaleX>
            <scaleY>0.6</scaleY>
            <rotationAngle>0.0</rotationAngle>
            <rotationOffset>0.0</rotationOffset>
            <transX>0.0</transX>
            <transY>0.0</transY>
            <renderer>F_blue_255</renderer>
        </key>
    </keys>
</animator>

=== brogan/Loom_2026/bezier/resources/animators/spin_scale.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE animator SYSTEM "../dtd/animator.dtd">
<animator>
    <name>spin_scale</name>
    <keys>
        <key>
            <duration>60.0</duration>
            <tweenMode>TWEENING</tweenMode>
            <easeMode>easeInOutSine</easeMode>
            <oscillator>none</oscillator>
            <scaleX>0.0</scaleX>
            <scaleY>0.0</scaleY>
            <rotationAngle>0.0</rotationAngle>
            <rotationOffset>0.0</rotationOffset>
            <transX>0.0</transX>
            <transY>0.0</transY>
            <renderer>F_blue_255</renderer>
        </key>
        <key>
            <duration>60.0</duration>
            <tweenMode>TWEENING</tweenMode>
            <easeMode>easeInOutSine</easeMode>
            <oscillator>none</oscillator>
            <scaleX>3.0</scaleX>
            <scaleY>3.0</scaleY>
            <rotationAngle>720.0</rotationAngle>
            <rotationOffset>0.0</rotationOffset>
            <transX>0.0</transX>
            <transY>0.0</transY>
            <renderer>F_blue_255</renderer>
        </key>
    </keys>
</animator>

=== brogan/Loom_2026/bezier/resources/animators/reverse.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE animator SYSTEM "../dtd/animator.dtd">
<animator>
    <name>reverse</name>
    <keys>
        <key>
            <duration>180.0</duration>
            <tweenMode>DISCRETE</tweenMode>
            <easeMode>linear</easeMode>
            <oscillator>osc_01</oscillator>
            <scaleX>-1.0</scaleX>
            <scaleY>1</scaleY>
            <rotationAngle>0.0</rotationAngle>
            <rotationOffset>0.0</rotationOffset>
            <transX>0.0</transX>
            <transY>0.0</transY>
            <renderer>F_blue_255</renderer>
        </key>
    </keys>
</animator>
