=== brogan/Loom_2026/bezier/resources/dtd/polygonSet.dtd
<!ELEMENT polygonSet (name, shapeType, polygon+, scaleX, scaleY, rotationAngle, transX, transY)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT shapeType (#PCDATA)>
<!ELEMENT polygon (curve+)>
   <!ELEMENT curve (point+)>
      <!ELEMENT point EMPTY>
         <!ATTLIST point x CDATA #REQUIRED>
         <!ATTLIST point y CDATA #REQUIRED>
<!ELEMENT scaleX (#PCDATA)>
<!ELEMENT scaleY (#PCDATA)>
<!ELEMENT rotationAngle (#PCDATA)>
<!ELEMENT transX (#PCDATA)>
<!ELEMENT transY (#PCDATA)>

=== brogan/Loom_2026/bezier/resources/shapes/polygonSet/Small_Centred_Squareb.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE polygonSet SYSTEM "../../dtd/polygonSet.dtd">
<polygonSet>
    <name>Small_Centred_Squareb</name>
    <shapeType>CUBIC_CURVE</shapeType>
    <polygon>
        <curve>
            <point x="-0.08000000000000002" y="-0.08000000000000002"/>
            <point x="-0.013333333333333308" y="-0.08000000000000002"/>
            <point x="0.053333333333333344" y="-0.08000000000000002"/>
            <point x="0.12" y="-0.08000000000000002"/>
        </curve>
        <curve>
            <point x="0.12" y="-0.08000000000000002"/>
            <point x="0.12" y="-0.013333333333333308"/>
            <point x="0.12" y="0.053333333333333344"/>
            <point x="0.12" y="0.12"/>
        </curve>
        <curve>
            <point x="0.12" y="0.12"/>
            <point x="0.053333333333333344" y="0.12"/>
            <point x="-0.013333333333333364" y="0.12"/>
            <point x="-0.08000000000000002" y="0.12"/>
        </curve>
        <curve>
            <point x="-0.08000000000000002" y="0.12"/>
            <point x="-0.08000000000000002" y="0.053333333333333344"/>
            <point x="-0.08000000000000002" y="-0.013333333333333364"/>
            <point x="-0.08000000000000002" y="-0.08000000000000002"/>
        </curve>
    </polygon>
    <scaleX>1.0</scaleX>
    <scaleY>1.0</scaleY>
    <rotationAngle>0.0</rotationAngle>
    <transX>0.5</transX>
    <transY>0.5</transY>
</polygonSet>
