=== brogan/Loom_2026/bezier/resources/dtd/regularPolygon.dtd
<!ELEMENT regularPolygon (name, shapeType, totalPoints, internalRadius, offset, scaleX, scaleY, rotationAngle, transX, transY)>

    <!ELEMENT name (#PCDATA)>
    <!ELEMENT shapeType (#PCDATA)>
    <!ELEMENT totalPoints (#PCDATA)>
    <!ELEMENT internalRadius (#PCDATA)>
    <!ELEMENT offset (#PCDATA)>
    <!ELEMENT scaleX (#PCDATA)>
    <!ELEMENT scaleY (#PCDATA)>
    <!ELEMENT rotationAngle (#PCDATA)>
    <!ELEMENT transX (#PCDATA)>
    <!ELEMENT transY (#PCDATA)>

=== brogan/Loom_2026/bezier/resources/shapes/regularPolygon/r_heptagon.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE regularPolygon SYSTEM "../../dtd/regularPolygon.dtd">
<regularPolygon>
    <name>r_heptagon</name>
    <shapeType>REGULAR_POLYGON</shapeType>
    <totalPoints>7</totalPoints>
    <internalRadius>0.5</internalRadius>
    <offset>0.0</offset>
    <scaleX>1.0</scaleX>
    <scaleY>1.0</scaleY>
    <rotationAngle>0.0</rotationAngle>
    <transX>0.5</transX>
    <transY>0.5</transY>
</regularPolygon>

=== brogan/Loom_2026/bezier/resources/shapes/regularPolygon/r_star_16.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE regularPolygon SYSTEM "../../dtd/regularPolygon.dtd">

<regularPolygon>

	<name>r_star_16</name>
	<shapeType>REGULAR_POLYGON</shapeType>
	<totalPoints>16</totalPoints>
	<internalRadius>2</internalRadius>
	<offset>0</offset>
	<scaleX>1</scaleX>
	<scaleY>1</scaleY>
	<rotationAngle>22.5</rotationAngle>
	<transX>.5</transX>
	<transY>.5</transY>

</regularPolygon>

=== brogan/Loom_2026/bezier/resources/shapes/regularPolygon/r_square.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE regularPolygon SYSTEM "../../dtd/regularPolygon.dtd">

<regularPolygon>

	<name>r_square</name>
	<shapeType>REGULAR_POLYGON</shapeType>
	<totalPoints>4</totalPoints>
	<internalRadius>.5</internalRadius>
	<offset>0</offset>
	<scaleX>1</scaleX>
	<scaleY>1</scaleY>
	<rotationAngle>45</rotationAngle>
	<transX>.5</transX>
	<transY>.5</transY>

</regularPolygon>
