=== brogan/Loom_2026/bezier/resources/dtd/renderer.dtd
<!ELEMENT renderer (name, mode, fillRed, fillGreen, fillBlue, fillAlpha, strokeRed, strokeGreen, strokeBlue, strokeAlpha, strokeWeight)>

    <!ELEMENT name (#PCDATA)>
    <!ELEMENT mode (#PCDATA)>
    <!ELEMENT fillRed (#PCDATA)>
    <!ELEMENT fillGreen (#PCDATA)>
    <!ELEMENT fillBlue (#PCDATA)>
    <!ELEMENT fillAlpha (#PCDATA)>
    <!ELEMENT strokeRed (#PCDATA)>
    <!ELEMENT strokeGreen (#PCDATA)>
    <!ELEMENT strokeBlue (#PCDATA)>
    <!ELEMENT strokeAlpha (#PCDATA)>
    <!ELEMENT strokeWeight (#PCDATA)>

=== brogan/Loom_2026/bezier/resources/renderers/F_black_255.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE renderer SYSTEM "../dtd/renderer.dtd">
<renderer>
    <name>F_black_255</name>
    <mode>RENDER_FILLED</mode>
    <fillRed>0</fillRed>
    <fillGreen>0</fillGreen>
    <fillBlue>0</fillBlue>
    <fillAlpha>255</fillAlpha>
    <strokeRed>255</strokeRed>
    <strokeGreen>255</strokeGreen>
    <strokeBlue>255</strokeBlue>
    <strokeAlpha>10</strokeAlpha>
    <strokeWeight>1</strokeWeight>
</renderer>

=== brogan/Loom_2026/bezier/resources/renderers/PT_black_.1_10.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE renderer SYSTEM "../dtd/renderer.dtd">
<renderer>
    <name>PT_black_.1_10</name>
    <mode>RENDER_POINTS</mode>
    <fillRed>250</fillRed>
    <fillGreen>20</fillGreen>
    <fillBlue>100</fillBlue>
    <fillAlpha>200</fillAlpha>
    <strokeRed>0</strokeRed>
    <strokeGreen>0</strokeGreen>
    <strokeBlue>0</strokeBlue>
    <strokeAlpha>10</strokeAlpha>
    <strokeWeight>.1</strokeWeight>
</renderer>

=== brogan/Loom_2026/bezier/resources/renderers/LN_white_1_10.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE renderer SYSTEM "../dtd/renderer.dtd">
<renderer>
    <name>LN_white_1_10</name>
    <mode>RENDER_LINES</mode>
    <fillRed>250</fillRed>
    <fillGreen>20</fillGreen>
    <fillBlue>100</fillBlue>
    <fillAlpha>200</fillAlpha>
    <strokeRed>255</strokeRed>
    <strokeGreen>255</strokeGreen>
    <strokeBlue>255</strokeBlue>
    <strokeAlpha>10</strokeAlpha>
    <strokeWeight>1.0</strokeWeight>
</renderer>
